### ISSUE TITLE
When changing the zoom value on the extension. Only new site are impacted

### ISSUE THREAD

**Issue by Taryck** [jamielinux/default-zoom#2]
Hi,

When I sent zoom level to 120% and open a unvisted site it's zoom level is 120%
Then I set the zoom level to 200% and open the same site it's still at 120%
If I open another unvisted site it's zoom level is at 200%

I seams that when using the extention instead of changing the default zoomlevel we recorde a defined zoom level for the site.
Could you just replace defaut 100% by the value in the extension and let only manual zoom level change do the recording ?
If it's possible.

**Comment by rathann** [comment]
Try setting `browser.zoom.siteSpecific` to `false` in `about:config`.

**Comment by Taryck** [comment]
Thanks, but I also need SiteSpecific zoom as some site are really too small.

**Comment by jamielinux** [comment]
Hi @Taryck, thanks for opening this issue!

You are correct that Firefox records a zoom level for every website. And I agree with you that ideally Firefox should only record site-specific zoom when the user manually changes from the `default-zoom` default.

Unfortunately, WebExtensions don't give you an easy way to do that.

One method would be to change `default-zoom` to keep its own list of zoom levels for every website, but I wanted to avoid this to keep the addon very simple/minimal. This method is what most of the other zoom addons do.

Probably the only workaround is the suggestion from @rathann above. I use that setting myself in fact.
