### ISSUE TITLE
Different #anchors treated as different sites

### ISSUE THREAD

**Issue by OJFord** [jamielinux/default-zoom#4]
This extension was exactly what I was looking for as I found myself changing site-specific zoom to around 80% everywhere I visited. Sometimes, however, I want something other than my default 80%.

The problem is that if I change from the default, say to 100%, on a specific site, then following links to elsewhere on the same page (e.g. `https://wikipedia.org/wiki/some-article#some-section`) resets to the default zoom level of 80%.

I would expect that my change to 100% (or whatever) would apply domain-wide, not just to the exact URL.

(It's particularly annoying in SPAs that use it for navigation.)

**Comment by jamielinux** [comment]
Hi @OJFord, thanks for the bug report!

### Short answer

Per-site zoom levels are respected, with one exception: a zoom level of 100% is always overridden after you navigate or reload.

There's a limitation in the WebExtension API. Other add-ons solve that by storing its own database of per-site zoom level entries for every website you visit. This add-on avoids that by only zooming when the zoom of the current tab is 100%.

### Long answer

Firefox stores site-specific zoom levels in a database. Unfortunately, the WebExtension API doesn't really let you read/manipulate this database or how zoom levels are added.

If you've set `default-zoom` to X%, when you navigate to a website the add-on will check the current zoom level and do this:

- If the current zoom is 100%, this is probably a new website. Change the zoom level to X%. 
- If the current zoom is anything else (eg, X% or 150%) then it's site-specific. Do nothing.

Unfortunately, **when the current zoom is 100%, there's not an easy way to tell if this is a new website or whether the user has intentionally set the zoom to 100%** (like in your case).

Most of the other zoom add-ons solve that by creating their own database to store per-site zoom level entries for every website you visit (essentially duplicating the functionality that Firefox is already doing). That's a perfectly reasonable approach.

**To keep this add-on minimal I went for a different approach, with the caveat that it's then no longer possible to save a site-specific zoom-level of 100%.** This is an acceptable trade-off for users with HiDPI screens or accessibility needs where 100% is likely to always be too small (which are the main audience for this add-on). I readily admit it doesn't suit users like yourself that want a default of below 100%. Unfortunately, I don't know a good way of accommodating for your use-case without changing the minimalist approach to this add-on, so I can only suggest you explore some of the other zoom add-ons. Sorry!

**Comment by OJFord** [comment]
My default was 80%, and it was 90% I changed to that was not persisted.

**Comment by jamielinux** [comment]
> My default was 80%, and it was 90% I changed to that was not persisted.

In your original post, you used 100% as an example. It happens by design in the case of 100% (as described above). In the case of 90% or anything else, I don't think that should happen. I tried to reproduce as follows:

1. Set default to 80%
2. Go to https://en.wikipedia.org/wiki/Firefox
3. Change current zoom to 90%
4. Go to https://en.wikipedia.org/wiki/Firefox#History
5. Zoom stays at 90%

If you're able to provide some steps to reproduce your issue then I'll gladly try to reproduce myself!
